### ISSUE TITLE
bones animation﻿n﻿ and TRS﻿ animation﻿n﻿﻿

### ISSUE THREAD

**Issue by shenzhuxi** [Kupoman/blendergltf#138] opened 2018-04-28 17:53 UTC
I can't get animation weight working with Babylon.js, so I asked and got answer here http://www.html5gamedevs.com/topic/37241-animationgroup-weight-and-blending-are-not-working-for-certain-gltf-file/?do=findComment&comment=213049
"You must export for model with bones animatio﻿n﻿ and not direct﻿ TRS﻿ animatio﻿n﻿﻿﻿ ﻿for every single mesh﻿"
Seems it's a problem of ht exporter. 
BTW, weights are working in three.js https://jsfiddle.net/shenzhuxi/hvvz9bc8/... strange...

**Comment by Kupoman** [comment] 2018-04-29 00:59
@shenzhuxi Thanks for reporting an issue. Unfortunately, I don't understand what the issue is. Is there some transforms that want to have exported as matrices instead of separate translation, rotation, and scale values? Also, could you please provide a .blend file that demonstrates the problem?

**Comment by shenzhuxi** [comment] 2018-04-30 10:27
It's explained here
http://www.html5gamedevs.com/topic/37241-animationgroup-weight-and-blending-are-not-working-for-certain-gltf-file/?tab=comments#comment-213246. 
Seems it's not really an error in the model.

**Comment by Kupoman** [comment] 2018-04-30 14:44
I am glad to hear you got it figured out. Since it looks like you are not encountering a bug with this exporter, I am closing this issue.

**Closed as completed by Kupoman** 2018-04-30 14:44 UTC
