### ISSUE TITLE
Additional meshes (for example, eyes or hair) exported in wrong positions?

### ISSUE THREAD

**Issue by Pivotxyz** [Kupoman/blendergltf#115] opened 2017-11-22 05:53 UTC
Hi, i was following a nice tutorial that employs this exporter (https://medium.com/@donmccurdy/creating-animated-gltf-characters-with-mixamo-and-blender-728dc120e678), but i´m having an issue when exporting the character from Blender, everything seems fine in blender, but after exporting I get this:

![hair_eyes_issue](https://user-images.githubusercontent.com/33888762/33111941-a69f7dc4-cf1e-11e7-8f91-3dcccba569b4.png)

The eyeballs meshes and the hair mesh, are at the bottom of the model and centered, it moves with the top bone of the rig, yet it shows in a different position.

It looks really fine in blender, but after exporting it shows like the previous image.

**Comment by Kupoman** [comment] 2017-11-22 17:26
It's hard for me to know what is going on without the .blend file to play with. Are there any bone parents involved, or is everything parented to the armature?

**Comment by Pivotxyz** [comment] 2017-11-22 22:03
Hey, updating here,  its fixed luckily, well as I said the model and the animation looked perfectly in Blender, I even opened the file in 3DSmax, and the objects were parented to the head bone that Mixamo exported, so all in all, I noticed that the "manipulator" pivot, was set at the feet of the girl, so i changed it by moving the pivot (object center) more to the torso, exported the fbx from 3ds, load it in mixamo, load  it then in Blender, and exporting, this time everything went fine, hair and eyes were at the right positions.

Really don´t know if its a bug of the exporter, and i didn´t know also that the object pivot of the software was relevant for exporting, thought all was managed by the bones rigging.

**Comment by Kupoman** [comment] 2017-11-23 03:09
Bone parenting in general has not been well tested. I would like to start using this issue to track problems with bone parenting and start improving bone parenting support.

**Comment by sctincman** [comment] 2017-11-27 23:31
As a temporary workaround, I've had good results with going to object mode, selecting both the mesh and armature and setting them both to have a common origin using Ctrl-Alt-Shift-C and selecting "Origin to 3D cursor" after placing my cursor in the desired.

Does the exporter assume a common origin for objects?

**Comment by Kupoman** [comment] 2018-01-25 04:57
I think I misunderstood what was going in here since bone parents were not working at all. Rereading the report, it sounds like it might be related to the problems being seen in #114 when the mesh and armatures have different origins. I am closing this issue as a duplicate of #114. Please reopen with an example file if you feel the problem is different.

**Closed as completed by Kupoman** 2018-01-25 04:57 UTC
Labels: bug
